name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # Or your preferred runner environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Bypass Cloudflare for GitHub Action
      uses: xiaotianxt/bypass-cloudflare-for-github-action@v2.0.1
      with:
        cf_account_id: ${{ secrets.CF_ACCOUNT_ID }}
        cf_zone_id: ${{ secrets.CF_ZONE_ID }}
        cf_api_token: ${{ secrets.CF_API_TOKEN }}      

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4' # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Robot Framework tests
      run: |
        if ! robot --outputdir results --exclude skip tests/; then
              echo "Robot Framework tests failed. Rerunning failed tests..."
              if [ -f results/output.xml ]; then
                  robot --rerunfailed results/output.xml --outputdir results_rerun tests/ || true
                  if [ -f results_rerun/output.xml ]; then
                      rebot --output results/output.xml --log results/log.html --report results/report.html --merge results/output.xml results_rerun/output.xml
                  else
                      echo "No output.xml file found from rerun. Skipping merge."
                  fi
              else
                  echo "No output.xml file found. Cannot rerun failed tests."
              fi
          fi
      continue-on-error: true
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./results
        name: robot-test-results
        retention-days: 3
